name: Build and Test Nightly
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build-and-test-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: robocup_client

      - name: Add nightly Debian repository and rosdep sources list
        run: |
          sudo apt update && sudo apt install curl
          curl -s http://repository.ichiro-its.org/debian/setup-nightly.bash | bash -s
          curl -s http://repository.ichiro-its.org/rosdep/setup.bash | bash -s

      - name: Build and test workspace
        uses: ichiro-its/ros2-build-and-test-action@main 
        with:
          pre-build: rosdep install --from-paths ~/ros2_foxy/ros2-linux/share --ignore-src --rosdistro foxy -y --skip-keys "console_bridge fastcdr fastrtps osrf_testing_tools_cpp poco_vendor rmw_connext_cpp rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rti-connext-dds-5.3.1 tinyxml_vendor tinyxml2_vendor urdfdom urdfdom_headers"
